### PR TITLE
Update to 0.22.0

### PR DESCRIPTION
**Pull request by synecdoche**
@rram @bsimpson63 :eyeglasses: 

All the gritty details are in `debian/README.debian`.

### CODE REVIEW

**Comment by synecdoche** [comment]
@bsimpson63 @rram Could I get more review on this?

**Comment by bsimpson63** [comment]
I'll do a review pass today, sorry about that

**Comment by bsimpson63** [comment]
Is there a way to structure this pull request to exclude all the official commits between the old and new version? Maybe you could make a branch that has all those comments, and then make this pull req relative to that one?

**Comment by synecdoche** [comment]
I'll try closing this and reopening two separate ones: one for upstream changes, and one for our changes.

**Pull request closed without merging**
