### PR TITLE
Update to v22 with static linking for FB libs

### PR DESCRIPTION
**Pull request by synecdoche**
:eyeglasses: @rram @bsimpson63 @spladug 

Update with lots of the feedback from https://github.com/synecdoche/mcrouter/pull/1

### CODE REVIEW

**Comment by synecdoche** [comment]
bump

:eyeglasses: @rram @bsimpson63

**Comment by synecdoche** [comment]
or does this actually do the bump? hmm, not sure

:haircut: @rram @bsimpson63

**Comment by bsimpson63** [comment]
Does this pull request contain anything new from https://github.com/synecdoche/mcrouter/pull/1? Could you keep using that pull request instead of creating a new one?

**Comment by synecdoche** [comment]
https://github.com/reddit/mcrouter/pull/1 was just our packaging commits for review. It didn't have the upstream changes, so it couldn't be committed. This PR contains the upstream Mcrouter commits, plus the packaging changes squashed down, per @rram's request, plus the following cleanup items that he requested:
- `buildall.sh` is cleaned up a bit
- `--whole-archive` linker flag removed

**Comment by synecdoche** [comment]
bump 

:haircut: @rram

**Pull request closed without merging**
